[package]
name = "ibdgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
derive_builder = "0.20.2"
nalgebra = "0.33.2"
pretty-print-nalgebra = "0.1.0"
rand = "0.8.5"
clap = { version = "4.4", features = ["derive"] }
